### ISSUE TITLE
OutOfMemoryError on httl.Engine.parseTemplate

### ISSUE THREAD

**Issue by pete-experimenter** [httl/httl#185]
Loop below will cause OOM, as the engine does not cache expressions vs templates.
```
for(int=0;i<10000;i++)
httl.Engine.parseTemplate("${2 + 2}")
```

I think it should cache as for files. It is unlikely that somebody is going to create diffrent expressions everytime, in which case it does not make sense to cache them. But it is the opposite the same expressions are to be used with different prarameters, in which case it does make sense to cache the expressions. 
Or at least please make it optional.

**Comment by icode** [comment]
Template not `el` expression
