### ISSUE TITLE
国际化message.basename是否支持多个文件？

### ISSUE THREAD

**Issue by fangstao** [httl/httl#191]
怎么像其他配置一样配置多个国际化配置文件？message.basenames=/WEB-INF/L1,/WEB-INF/L2

**Comment by icode** [comment]
你可以实现一个你自己的用于多个，模板还没有提供这样的功能，我现在也米有时间去写，你可以参考我的框架的做法 
1. 多文件加载实现 https://github.com/icode/ameba/tree/master/src/main/java/ameba/i18n
2. 用于替换httl原有i18n实现https://github.com/icode/ameba/blob/master/src/main/java/ameba/mvc/template/httl/internal/MessageMethod.java
