### ISSUE TITLE
build new binary jar file

### ISSUE THREAD

**Issue by azimot** [httl/httl#198]
I see version of jar file in "http://httl.github.io/en/" and "http://httl.github.io/en/download.html"  is yet "1.0.11"

Please update it to "1.0.12" and make new change log of "1.0.12"

Thanks

**Comment by tomwhoiscontrary** [comment]
:+1:

In the mean time, two other parties have uploaded 1.0.12 to Maven Central:

http://search.maven.org/#search|ga|1|a%3A%22httl%22%20AND%20v%3A%221.0.12%22

**Comment by icode** [comment]
```xml
<dependency>
    <groupId>org.amebastack.template</groupId>
    <artifactId>httl</artifactId>
    <version>1.0.12</version>
</dependency>
```
