### ISSUE TITLE
Constants as Map key

### ISSUE THREAD

**Issue by SeraphicRav** [httl/httl#199]
Hi !

I tried to use an enum as a key in the Map I provide to template.render but all my placeholders are not replaced by their value. It seems that the name of the enum or toString value is not used but something else is.

For instance (The following code represents the idea of our code but not the actual one) :
public enum MyEnum {
  KEY
}

class Test {
  ...
  public void test(){
    //Object initialization
    Map<MyEnum, Object> map = new HashMap<MyEnum, Object>();
    map.put(MyEnum.KEY, "Hi !");
    // Cal to template
  }
}

In the template :
${KEY}

Result : I do not see "Hi !" in the generated HTML but "" instead.

Best regards !

**Comment by icode** [comment]
You can use 1.0.12 version, and ```import(MyEnum)```,then ```${MyEnum.KEY}```

**Comment by icode** [comment]
```xml
<dependency>
    <groupId>org.amebastack.template</groupId>
    <artifactId>httl</artifactId>
    <version>1.0.12</version>
</dependency>
```

**Comment by SeraphicRav** [comment]
Thanks !
