### ISSUE TITLE
能否增加多语言文件的支持？

### ISSUE THREAD

**Issue by storezhang** [httl/httl#203]
国际化的时候只有一个语言文件，字符串太多，难以管理！

**Comment by icode** [comment]
httl接口很开放，可以自己实现一下，像这样  https://github.com/icode/ameba/tree/master/src/main/java/ameba/i18n

另外推荐下自己的框架 :smile:

**Comment by icode** [comment]
还有就是我不太明白如何支持多个，我的ameba框架是通过不同模块的i18n文件组合在一起实现的，你要如何实现？配置么？

**Comment by storezhang** [comment]
没时间啊，最近被一个内在泄漏搞得头大！

**Comment by storezhang** [comment]
你是如何实现的？

**Comment by icode** [comment]
每个模块有自己的i18n文件，都是一个名字，读取的时候分别读取合并在一起

**Comment by storezhang** [comment]
那多麻烦

**Comment by icode** [comment]
不然如何设计？

2015-11-16 11:43 GMT+08:00, storezhang notifications@github.com:

**Comment by storezhang** [comment]
读取目录，目录下的文件名按模块命名

**Comment by icode** [comment]
晕，你不懂模块的意思么？一个模块就是一个jar。你这个思路不对，java本来就有这个支持，同目录下相同名字 后缀以_zh(语言代码)结尾的都视为语言包文件（BUNDLE）。你这设计不同国家语言文件如何存放？

**Comment by storezhang** [comment]
你说的是真正意义上的模块吧，我说的是只是文件管理上的模块。就好比httl会有一个配置多语言的配置，如果这儿是一个目录，我在下面可以根据不同的功能分成不同的文件，以后添加或者修改的时候能一眼看出要改什么文件，而不是在代码里面一层一层的去找。

**Comment by storezhang** [comment]
看了下代码，我还是自己来实现吧。另外，你的QQ多少？我加下你，请教一下Java Filter内存问题

**Comment by icode** [comment]
icode@log4ic.com  主显账号

嗯，我设计哪个接口是需要自己传入一个i18n文件的，可以做到你需要的，只是需要自己写一个文件，你可以抽取出来一个工具类

**Comment by storezhang** [comment]
我只增加到HTTL里面去
