### ISSUE TITLE
How to enable accessing deeply nested properties ?

### ISSUE THREAD

**Issue by albert-kam** [httl/httl#231]
Hi guys,

I'm having a problem where httl engine cannot see the object type if i do it this way:
```
$!{extends('/template/main/layout.httl')}
<!-- #macro(body) -->
<!-- #set(FormMapping<ListRegisteredUser> form) -->
	<p>${form.fields.page.labelKey}</p>
<!-- #end -->
```

But it works fine if i specify it like this, which prooves the import.packages works in httl.properties:
```
$!{extends('/template/main/layout.httl')}
<!-- #macro(body) -->
<!-- #set(FormMapping<ListRegisteredUser> form) -->
<!-- #set(Map<String, FormField> fields=form.fields) -->
<!-- #set(FormField pageField=fields.page) -->
  <p>${pageField.labelKey}</p>
<!-- #end -->

```
Any suggestions so that i could access properties deeply without setting the variable type for each nesting ?

Thank you,
Albert Gan

**Comment by muziapple** [comment]
hi Albert,

  seems httl doesn't support that, refer to doc

`Note: only supports List and Map of a generic, multi-level generic able to resolve, but not derived.`

  I'm not sure if there is an extension point, you may need tell engine the structure of your FormMapping OR customize #set directive

**Comment by albert-kam** [comment]
Thank you for clearing things up
